{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "script": [
    "qmake -project",
    "qmake TravisTest.pro",
    "make"
  ],
  "language": "cpp",
  "before_install": [
    "sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y",
    "sudo apt-get update",

  ],
  "install":[
    "sudo apt-get install qtbase510-dev qtdeclarative510-dev"
    "source /opt/qt510/bin/qt510-env.sh"
  ]
}